// src/context/LanguageContext.jsx
import { createContext, useContext, useState } from 'react';

const translations = {
  mg: {
    home: 'Fandraisana', profile: 'Mombamomba', friends: 'Namana',
    messages: 'Hafatra', notifications: 'Fampandrenesana', settings: 'Fikirana',
    logout: 'Hivoaka', login: 'Hiditra', register: 'Misoratra',
    email: 'Mailaka', password: 'Teny miafina', name: 'Anarana',
    post: 'Mamoaka', comment: 'Hevitra', like: 'Tia', share: 'Zarao',
    addFriend: 'Hanampy namana', removeFriend: 'Esory namana',
    friendRequest: 'Fangatahana namana', accept: 'Ekeo', decline: 'Ariana',
    send: 'Alefaso', message: 'Hafatra', typeMessage: 'Soraty hafatra...',
    search: 'Tadiavo...', addPhoto: 'Hanampy sary', addVideo: 'Hanampy video',
    sell: 'Amidy', price: 'Vidiny', publishPost: 'Mamoaka',
    whatsOnMind: 'Inona no hevitrao?', myPosts: 'Famoahana',
    mySales: 'Vente', myFriends: 'Ny namanako', editProfile: 'Ovao ny mombamomba',
    appearance: 'Endrika', language: 'Fiteny', deletePost: 'Fafao', editPost: 'Ovao',
    noNotifications: 'Tsy misy fampandrenesana', noMessages: 'Tsy misy hafatra',
    online: 'Ao an-tserasera', offline: 'Tsy ao', bio: 'Momba ahy',
    save: 'Tehirizo', cancel: 'Ajanony', loading: 'Miandry...', error: 'Nisy olana',
    welcomeTo: 'Tonga soa ao', createAccount: 'Mamorona kaonty',
    alreadyAccount: 'Manana kaonty sahady?', noAccount: 'Tsy manana kaonty?',
    fullName: 'Anarana feno', username: 'Anarana ampiasaina',
    confirmPassword: 'Avereno ny teny miafina', yourFriends: 'Ny namanao',
    suggestions: 'Soso-kevitra', noFriends: 'Tsy misy namana mbola',
    viewProfile: 'Jereo ny mombamomba', reactions: 'Fihetsika',
    allPosts: 'Famoahana rehetra', sale: 'Amidy', writeComment: 'Soraty hevitra...',
    pendingRequests: 'Fangatahana miandry',
    downloadMedia: 'Alaivo', copyLink: 'Adikeo ny lien',
    deleteNotification: 'Fafao', deleteMessage: 'Fafao ny hafatra',
    deleteConversation: 'Fafao ny resaka', mediaPosts: 'Sary & Video',
    coverPhoto: 'Sary fanamarihana', changeCover: 'Ovao ny sary fanamarihana',
    reels: 'Video fohy', deactivateAccount: 'Anjanony vonjimaika ny kaonty',
    deleteAccount: 'Fafao ny kaonty',
    deactivateConfirm: 'Tena anjanony ny kaonty ve?',
    deleteConfirm: 'Tena fafao TANTERAKA ny kaonty ve? Tsy azo averina!',
    accountDanger: 'Danger Zone', linkCopied: 'Adikina ny lien!',
    reply: 'Valiana', replyTo: 'Valiana an',
    searchMessages: 'Tadiavo resaka...', messageNonFriend: 'Alefaso hafatra',
  },
  fr: {
    home: 'Accueil', profile: 'Profil', friends: 'Amis',
    messages: 'Messages', notifications: 'Notifications', settings: 'Paramètres',
    logout: 'Se déconnecter', login: 'Se connecter', register: "S'inscrire",
    email: 'E-mail', password: 'Mot de passe', name: 'Nom',
    post: 'Publier', comment: 'Commenter', like: 'Aimer', share: 'Partager',
    addFriend: 'Ajouter ami', removeFriend: 'Retirer ami',
    friendRequest: "Demande d'ami", accept: 'Accepter', decline: 'Refuser',
    send: 'Envoyer', message: 'Message', typeMessage: 'Écrivez un message...',
    search: 'Rechercher...', addPhoto: 'Ajouter photo', addVideo: 'Ajouter vidéo',
    sell: 'Vendre', price: 'Prix', publishPost: 'Publier',
    whatsOnMind: 'Quoi de neuf ?', myPosts: 'Publications',
    mySales: 'Ventes', myFriends: 'Mes amis', editProfile: 'Modifier le profil',
    appearance: 'Apparence', language: 'Langue', deletePost: 'Supprimer', editPost: 'Modifier',
    noNotifications: 'Pas de notifications', noMessages: 'Pas de messages',
    online: 'En ligne', offline: 'Hors ligne', bio: 'Bio',
    save: 'Enregistrer', cancel: 'Annuler', loading: 'Chargement...', error: 'Une erreur est survenue',
    welcomeTo: 'Bienvenue sur', createAccount: 'Créer un compte',
    alreadyAccount: 'Déjà un compte ?', noAccount: 'Pas de compte ?',
    fullName: 'Nom complet', username: "Nom d'utilisateur",
    confirmPassword: 'Confirmer le mot de passe', yourFriends: 'Vos amis',
    suggestions: 'Suggestions', noFriends: 'Aucun ami pour le moment',
    viewProfile: 'Voir le profil', reactions: 'Réactions',
    allPosts: 'Toutes les publications', sale: 'Vente', writeComment: 'Écrire un commentaire...',
    pendingRequests: 'Demandes en attente',
    downloadMedia: 'Télécharger', copyLink: 'Copier le lien',
    deleteNotification: 'Supprimer', deleteMessage: 'Supprimer le message',
    deleteConversation: 'Supprimer la conversation', mediaPosts: 'Photos & Vidéos',
    coverPhoto: 'Photo de couverture', changeCover: 'Changer la couverture',
    reels: 'Vidéos courtes', deactivateAccount: 'Désactiver le compte',
    deleteAccount: 'Supprimer le compte',
    deactivateConfirm: 'Désactiver votre compte temporairement ?',
    deleteConfirm: 'Supprimer DÉFINITIVEMENT le compte ? Action irréversible !',
    accountDanger: 'Zone de danger', linkCopied: 'Lien copié !',
    reply: 'Répondre', replyTo: 'Répondre à',
    searchMessages: 'Rechercher une conversation...', messageNonFriend: 'Envoyer un message',
  },
  en: {
    home: 'Home', profile: 'Profile', friends: 'Friends',
    messages: 'Messages', notifications: 'Notifications', settings: 'Settings',
    logout: 'Logout', login: 'Login', register: 'Register',
    email: 'Email', password: 'Password', name: 'Name',
    post: 'Post', comment: 'Comment', like: 'Like', share: 'Share',
    addFriend: 'Add friend', removeFriend: 'Remove friend',
    friendRequest: 'Friend request', accept: 'Accept', decline: 'Decline',
    send: 'Send', message: 'Message', typeMessage: 'Type a message...',
    search: 'Search...', addPhoto: 'Add photo', addVideo: 'Add video',
    sell: 'Sell', price: 'Price', publishPost: 'Publish',
    whatsOnMind: "What's on your mind?", myPosts: 'Posts',
    mySales: 'Sales', myFriends: 'My friends', editProfile: 'Edit profile',
    appearance: 'Appearance', language: 'Language', deletePost: 'Delete', editPost: 'Edit',
    noNotifications: 'No notifications', noMessages: 'No messages',
    online: 'Online', offline: 'Offline', bio: 'Bio',
    save: 'Save', cancel: 'Cancel', loading: 'Loading...', error: 'Something went wrong',
    welcomeTo: 'Welcome to', createAccount: 'Create account',
    alreadyAccount: 'Already have an account?', noAccount: "Don't have an account?",
    fullName: 'Full name', username: 'Username',
    confirmPassword: 'Confirm password', yourFriends: 'Your friends',
    suggestions: 'Suggestions', noFriends: 'No friends yet',
    viewProfile: 'View profile', reactions: 'Reactions',
    allPosts: 'All posts', sale: 'Sale', writeComment: 'Write a comment...',
    pendingRequests: 'Pending requests',
    downloadMedia: 'Download', copyLink: 'Copy link',
    deleteNotification: 'Delete', deleteMessage: 'Delete message',
    deleteConversation: 'Delete conversation', mediaPosts: 'Photos & Videos',
    coverPhoto: 'Cover photo', changeCover: 'Change cover',
    reels: 'Short videos', deactivateAccount: 'Deactivate account',
    deleteAccount: 'Delete account',
    deactivateConfirm: 'Deactivate your account temporarily?',
    deleteConfirm: 'PERMANENTLY delete account? Cannot be undone!',
    accountDanger: 'Danger Zone', linkCopied: 'Link copied!',
    reply: 'Reply', replyTo: 'Reply to',
    searchMessages: 'Search conversations...', messageNonFriend: 'Send message',
  },
};

const LanguageContext = createContext();
export function LanguageProvider({ children }) {
  // Default: français
  const [lang, setLang] = useState(localStorage.getItem('tsengo_lang') || 'fr');
  const changeLang = (l) => { setLang(l); localStorage.setItem('tsengo_lang', l); };
  const t = (key) => translations[lang]?.[key] || translations['fr'][key] || key;
  return <LanguageContext.Provider value={{ lang, changeLang, t }}>{children}</LanguageContext.Provider>;
}
export const useLang = () => useContext(LanguageContext);
